    - name: open_apache_port
      firewalld: service=http
                 permanent=true
                 state=enabled
                 immediate=yes

    - name: open_apache_secure_port
      firewalld: service=https
                 permanent=true
                 state=enabled
                 immediate=true

    - name: restart_apache
      service: name=httpd
               state=restarted
