    - name: open_apache_port
      firewalld: port=80/tcp
                 permanent=true
                 state=enabled
                 immediate=yes

    - name: open_apache_secure_port
      firewalld: port=443/tcp
                 permanent=true
                 state=enabled
                 immediate=true

    - name: restart_apache
      service: name=httpd
               state=restarted
