---
    # First update existing yum repos packages
    - name: Update yum
      yum: name=*
           update_cache=yes
           state=latest

    # Install the required devel packages
    - name: Install Core Development Tools
      yum: name="@Development tools"
           update_cache=yes
           state=latest

    # Install policycoreutils-python for SELinux changes
    - name: Install policycoreutils-python
      yum: name=policycoreutils-python
           update_cache=yes
           state=latest
